ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1SyncEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1LoginEmail" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1PasswordEnc" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1SessionEnc" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1LastSyncAt" TIMESTAMP(3);
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1LastSyncError" TEXT;
ALTER TABLE "OrgSettings" ADD COLUMN IF NOT EXISTS "micro1LastSyncStats" JSONB;
