-- Job staffing / detail fields
DO $$ BEGIN
  CREATE TYPE "JobPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "jobFunction" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "priority" "JobPriority" NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "billRateMin" DECIMAL(65,30);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "billRateMax" DECIMAL(65,30);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "payRateMin" DECIMAL(65,30);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "payRateMax" DECIMAL(65,30);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "ratePeriod" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "zip" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "address1" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "address2" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "maxSubmissions" INTEGER;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3);
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "requireResume" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "travelRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "otRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "referencesRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "drugTestRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "backgroundCheckRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "securityClearanceRequired" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "JobNote" (
  "id" TEXT NOT NULL,
  "organizationId" TEXT NOT NULL,
  "jobId" TEXT NOT NULL,
  "authorId" TEXT,
  "body" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "JobNote_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "JobNote_jobId_createdAt_idx" ON "JobNote"("jobId", "createdAt");
CREATE INDEX IF NOT EXISTS "JobNote_organizationId_idx" ON "JobNote"("organizationId");

DO $$ BEGIN
  ALTER TABLE "JobNote" ADD CONSTRAINT "JobNote_organizationId_fkey"
    FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "JobNote" ADD CONSTRAINT "JobNote_jobId_fkey"
    FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "JobNote" ADD CONSTRAINT "JobNote_authorId_fkey"
    FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
