/** Normalized synonym groups for deterministic skill/title matching. */
export const SKILL_SYNONYM_GROUPS: string[][] = [
  ["python", "python3", "python 3"],
  ["javascript", "js", "ecmascript", "typescript", "ts"],
  ["react", "react.js", "reactjs"],
  ["node.js", "nodejs", "node"],
  ["kubernetes", "k8s"],
  ["amazon web services", "aws"],
  ["microsoft azure", "azure"],
  ["google cloud platform", "gcp", "google cloud", "google cloud platform (gcp)"],
  ["bigquery", "big query", "google bigquery"],
  ["data architect", "data architecture", "solutions architect"],
  ["rest api", "rest apis", "restful api", "restful apis", "restful services"],
  ["api development", "api services", "web services", "microservices"],
  ["postgresql", "postgres"],
  ["sql server", "mssql", "microsoft sql server"],
  ["machine learning", "ml", "deep learning"],
  ["ci/cd", "cicd", "continuous integration", "continuous delivery"],
  ["docker", "containerization", "containers"],
  ["terraform", "infrastructure as code", "iac"],
  ["jenkins", "github actions", "gitlab ci"],
  ["spring boot", "springboot", "spring framework"],
  ["fastapi", "flask", "django"],
  ["react native", "react-native"],
  ["power bi", "powerbi"],
  ["tableau", "looker", "data visualization"],
  ["snowflake", "databricks"],
  ["kafka", "apache kafka"],
  ["redis", "memcached"],
  ["mongodb", "mongo"],
  ["graphql", "graph ql"],
  ["scrum", "agile", "kanban"],
  ["team leadership", "leading teams", "people management"],
  ["mentoring", "coaching", "developing engineers"],
];

export const TITLE_SYNONYM_GROUPS: string[][] = [
  ["software engineer", "software developer", "developer", "programmer"],
  ["backend engineer", "back-end engineer", "backend developer", "server engineer"],
  ["frontend engineer", "front-end engineer", "frontend developer", "ui engineer"],
  ["full stack engineer", "fullstack engineer", "full-stack developer"],
  ["senior software engineer", "sr software engineer", "senior developer"],
  ["staff engineer", "principal engineer", "lead engineer"],
  ["data architect", "enterprise data architect", "solutions architect"],
  ["data engineer", "data platform engineer"],
  ["devops engineer", "platform engineer", "sre", "site reliability engineer"],
  ["python engineer", "python developer"],
  ["java engineer", "java developer"],
];

export const RESPONSIBILITY_EQUIVALENCES: Array<{ requirement: RegExp; evidence: RegExp }> = [
  { requirement: /design\s+rest\s+apis?/i, evidence: /(develop|built|design|created).{0,40}(rest|api)/i },
  { requirement: /optimi[sz]e\s+databases?/i, evidence: /(improv|optimi[sz]|tun).{0,40}(postgres|sql|database|query)/i },
  { requirement: /lead\s+(engineers?|teams?|developers?)/i, evidence: /(lead|led|managed|mentor).{0,40}(team|engineer|developer|sprint)/i },
  { requirement: /mentor/i, evidence: /(mentor|coached|trained).{0,40}(junior|engineer|developer|intern)/i },
  { requirement: /deploy/i, evidence: /(deploy|release|ship).{0,40}(production|cloud|aws|azure|gcp|kubernetes)/i },
  { requirement: /architect/i, evidence: /(architect|designed|system design)/i },
  { requirement: /code review/i, evidence: /(code review|peer review|pull request review)/i },
];

export const SOFT_SKILL_EVIDENCE: Array<{ skill: string; pattern: RegExp }> = [
  { skill: "Leadership", pattern: /(led|lead|managed|directed|head of|team lead)/i },
  { skill: "Communication", pattern: /(present|communicat|stakeholder|wrote|document)/i },
  { skill: "Collaboration", pattern: /(collaborat|cross-functional|partnered|worked with)/i },
  { skill: "Problem Solving", pattern: /(solved|troubleshoot|root cause|debug|resolved)/i },
  { skill: "Mentoring", pattern: /(mentor|coached|trained|onboarded)/i },
  { skill: "Ownership", pattern: /(owned|end-to-end|accountable|drove)/i },
  { skill: "Customer Focus", pattern: /(customer|client-facing|user experience|support)/i },
  { skill: "Analytical Thinking", pattern: /(analyz|metrics|data-driven|insights|forecast)/i },
];

export const INDUSTRY_KEYWORDS = [
  "healthcare",
  "finance",
  "financial services",
  "banking",
  "government",
  "automotive",
  "telecommunications",
  "retail",
  "saas",
  "manufacturing",
  "insurance",
  "education",
  "e-commerce",
  "energy",
  "aerospace",
  "defense",
  "pharma",
  "biotech",
];

export const COMMON_TOOLS = [
  "aws",
  "azure",
  "gcp",
  "docker",
  "kubernetes",
  "git",
  "jenkins",
  "terraform",
  "kafka",
  "snowflake",
  "power bi",
  "tableau",
  "excel",
  "sql server",
  "oracle",
  "jira",
  "confluence",
  "figma",
  "postman",
  "ansible",
  "helm",
  "prometheus",
  "grafana",
  "splunk",
  "datadog",
];

export const TRANSFERABLE_PLATFORM_PAIRS: Array<[string, string]> = [
  ["aws", "azure"],
  ["aws", "gcp"],
  ["azure", "gcp"],
  ["react", "vue"],
  ["react", "angular"],
  ["postgresql", "mysql"],
  ["kubernetes", "docker swarm"],
  ["jenkins", "github actions"],
  ["terraform", "cloudformation"],
];
